package view;

import dao.DaoGeneric;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.clan;
import model.jugador;
import model.partida;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author AluCiclesGS1
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // TODO add your handling code here:

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        estrelles1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        nom1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        copes1 = new javax.swing.JTextField();
        oro1 = new javax.swing.JTextField();
        gemes1 = new javax.swing.JTextField();
        nivell1 = new javax.swing.JTextField();
        crearJugador = new javax.swing.JButton();
        crearPartida = new javax.swing.JButton();
        nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        copes = new javax.swing.JTextField();
        oro = new javax.swing.JTextField();
        gemes = new javax.swing.JTextField();
        nivell = new javax.swing.JTextField();
        idjug1 = new javax.swing.JTextField();
        idjug2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        estrelles = new javax.swing.JTextField();
        ActualitzaJ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJ = new javax.swing.JTable();
        eliminarJugador = new javax.swing.JButton();
        id_jug = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        resultat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        temps = new javax.swing.JTextField();
        tipus = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaP = new javax.swing.JTable();
        actualitzaP = new javax.swing.JButton();
        eliminarJugador1 = new javax.swing.JButton();
        id_partida = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        copesC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jugadminC = new javax.swing.JTextField();
        tipusC = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        nomC = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaC = new javax.swing.JTable();
        nivellC = new javax.swing.JTextField();
        actualitzaC = new javax.swing.JButton();
        eliminarClan = new javax.swing.JButton();
        id_clan = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        crearClan = new javax.swing.JButton();

        jTextField8.setText("Nivell");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel7.setText("idjug1");

        jLabel10.setText("Copes");

        jLabel11.setText("Oro");

        jLabel12.setText("Gemes");

        jLabel13.setText("Nivell");

        jLabel14.setText("Estrelles");

        estrelles1.setText("estrelles");
        estrelles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estrelles1ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear Jugador");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        nom1.setText("nom");

        jLabel15.setText("Nom");

        copes1.setText("copes");

        oro1.setText("oro");
        oro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oro1ActionPerformed(evt);
            }
        });

        gemes1.setText("gemes");
        gemes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gemes1ActionPerformed(evt);
            }
        });

        nivell1.setText("nivell");
        nivell1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivell1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearJugador.setText("Crear Jugador");
        crearJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearJugadorActionPerformed(evt);
            }
        });

        crearPartida.setText("Crear Partida");
        crearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPartidaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        oro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oroActionPerformed(evt);
            }
        });

        gemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gemesActionPerformed(evt);
            }
        });

        nivell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivellActionPerformed(evt);
            }
        });

        idjug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjug1ActionPerformed(evt);
            }
        });

        idjug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjug2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Copes");

        jLabel3.setText("Oro");

        jLabel4.setText("Gemes");

        jLabel5.setText("Nivell");

        jLabel6.setText("idjug1");

        jLabel8.setText("idjug2");

        jLabel9.setText("Estrelles");

        estrelles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estrellesActionPerformed(evt);
            }
        });

        ActualitzaJ.setText("Actualitza Taula Jugadors");
        ActualitzaJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualitzaJActionPerformed(evt);
            }
        });

        tablaJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Copes", "Oro", "Gemes", "Nivell", "Estrelles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaJ);

        eliminarJugador.setText("Eliminar Jugador");
        eliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarJugadorActionPerformed(evt);
            }
        });

        jLabel21.setText("ID_Jug");

        jLabel16.setText("resultat");

        resultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultatActionPerformed(evt);
            }
        });

        jLabel17.setText("temps");

        temps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempsActionPerformed(evt);
            }
        });

        tipus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipusActionPerformed(evt);
            }
        });

        jLabel18.setText("tipus");

        tablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Partida", "Id_jug_1", "Id_jug_2", "Resultat", "Temps", "Tipus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaP);

        actualitzaP.setText("Actualitza Taula Partidas");
        actualitzaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualitzaPActionPerformed(evt);
            }
        });

        eliminarJugador1.setText("Eliminar Partida");
        eliminarJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPartidaActionPerformed(evt);
            }
        });

        jLabel22.setText("ID_Par");

        jLabel19.setText("Copes");

        copesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copesCActionPerformed(evt);
            }
        });

        jLabel20.setText("Jug Admin");

        jugadminC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadminCActionPerformed(evt);
            }
        });

        tipusC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipusCActionPerformed(evt);
            }
        });

        jLabel23.setText("Tipus");

        nomC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomCActionPerformed(evt);
            }
        });

        tablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Clan", "Nom", "Nivell", "Copes", "Jug Admin", "Tipus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaC);

        nivellC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivellCActionPerformed(evt);
            }
        });

        actualitzaC.setText("Actualitza Taula Clans");
        actualitzaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualitzaCActionPerformed(evt);
            }
        });

        eliminarClan.setText("Eliminar Clan");
        eliminarClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClanActionPerformed(evt);
            }
        });

        jLabel24.setText("ID_Clan");

        jLabel25.setText("Nom");

        jLabel26.setText("Nivell");

        crearClan.setText("Crear Clan");
        crearClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(crearJugador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarJugador)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(copes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gemes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nivell, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estrelles, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(221, 221, 221))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(37, 37, 37)
                        .addComponent(id_jug, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ActualitzaJ)
                .addGap(528, 528, 528))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel16))
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idjug2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temps, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipus, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idjug1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addGap(37, 37, 37)
                                .addComponent(id_partida, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(crearPartida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarJugador1)
                                .addGap(29, 29, 29)))))
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actualitzaP)
                .addGap(518, 518, 518))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actualitzaC)
                        .addGap(510, 510, 510))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(nomC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nivellC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(copesC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jugadminC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipusC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(37, 37, 37)
                        .addComponent(id_clan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(crearClan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarClan)
                        .addGap(248, 248, 248)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearJugador)
                    .addComponent(eliminarJugador))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(id_jug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(estrelles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(ActualitzaJ)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearPartida)
                            .addComponent(eliminarJugador1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idjug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idjug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(resultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(tipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_partida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(130, 130, 130)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualitzaP)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearClan)
                            .addComponent(eliminarClan))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nivellC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(copesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugadminC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipusC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_clan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualitzaC)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearJugadorActionPerformed
        try {
            jugador jug = new jugador(nom.getText(), Integer.parseInt(nivell.getText()),
                    Integer.parseInt(copes.getText()), Integer.parseInt(oro.getText()),
                    Integer.parseInt(gemes.getText()), Integer.parseInt(estrelles.getText()));
            //"xgaaa", 233, 123, "clanet", 12,333) ;
            DaoGeneric.getInstance().create(jug);
            //ju
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar " + e.getMessage());
        }
            }//GEN-LAST:event_crearJugadorActionPerformed

    private void oroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oroActionPerformed

    private void gemesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gemesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gemesActionPerformed

    private void nivellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivellActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void idjug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjug1ActionPerformed
        
    }//GEN-LAST:event_idjug1ActionPerformed

    private void idjug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjug2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjug2ActionPerformed

    private void estrellesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estrellesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estrellesActionPerformed

    private void ActualitzaJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualitzaJActionPerformed
        List llista = (List) DaoGeneric.getInstance().readJugador();
        DefaultTableModel model = (DefaultTableModel) tablaJ.getModel();
        model.setRowCount(0);

        for (int i = 0; i < llista.size(); i++) {

            jugador jug = (jugador) llista.get(i);
            //System.out.println(jug.getNom());
            Vector oneRow = new Vector () ;
            oneRow. add (Integer.toString(jug.getId() ) );
            oneRow. add (jug.getNom()) ;
            oneRow.add (Integer.toString(jug.getCopes()));
            oneRow. add (Integer.toString(jug.getNivell()));
            oneRow. add (Integer.toString(jug.getGemes()));
            oneRow.add (Integer.toString(jug.getOro()));
            //oneRow.add(jug.getClan ());
            model.addRow (oneRow);

        }

        tablaJ.setModel(model);
    }//GEN-LAST:event_ActualitzaJActionPerformed

    private void estrelles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estrelles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estrelles1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void oro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oro1ActionPerformed

    private void gemes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gemes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gemes1ActionPerformed

    private void nivell1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivell1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivell1ActionPerformed

    private void eliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarJugadorActionPerformed
        DaoGeneric.getInstance().deleteJugador(Integer.parseInt(id_jug.getText()));
    }//GEN-LAST:event_eliminarJugadorActionPerformed

    private void crearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPartidaActionPerformed
        try {
            partida par = new partida(Integer.parseInt(idjug1.getText()), Integer.parseInt(idjug2.getText()), 
                    resultat.getText(), temps.getText(), tipus.getText());
            //"xgaaa", 233, 123, "clanet", 12,333) ;
            DaoGeneric.getInstance().create(par);
            //ju
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar " + ex.getMessage());
        }
    }//GEN-LAST:event_crearPartidaActionPerformed

    private void resultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultatActionPerformed

    private void tempsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempsActionPerformed

    private void tipusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipusActionPerformed

    private void ActualitzaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualitzaPActionPerformed
        List llista = (List) DaoGeneric.getInstance().readPartida();
        DefaultTableModel model = (DefaultTableModel) tablaP.getModel();
        model.setRowCount(0);

        for (int i = 0; i < llista.size(); i++) {

            partida par = (partida) llista.get(i);
            //System.out.println(jug.getNom());
            Vector oneRow = new Vector () ;
            oneRow. add (Integer.toString(par.getId_partida()) );
            oneRow. add (par.getIdjug1());
            oneRow. add (par.getIdjug2());
            oneRow.add (par.getResultat());
            oneRow. add (par.getTemps());
            oneRow. add (par.getTipus());
            
            //oneRow.add(jug.getClan ());
            model.addRow (oneRow);

        }

        tablaP.setModel(model);
    }//GEN-LAST:event_ActualitzaPActionPerformed

    private void eliminarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPartidaActionPerformed
        DaoGeneric.getInstance().deletePartida(Integer.parseInt(id_partida.getText()));
    }//GEN-LAST:event_eliminarPartidaActionPerformed

    private void copesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copesCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copesCActionPerformed

    private void jugadminCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadminCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadminCActionPerformed

    private void tipusCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipusCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipusCActionPerformed

    private void nomCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomCActionPerformed

    private void nivellCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivellCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivellCActionPerformed

    private void actualitzaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualitzaCActionPerformed
        // Aqui ens carrega la llista que hem fet de la query en el daogeneric
        List llista = (List) DaoGeneric.getInstance().readClan();
        DefaultTableModel model = (DefaultTableModel) tablaC.getModel();
        model.setRowCount(0);

        // Fem un for per que ens mostri cada un dels parametres
        for (int i = 0; i < llista.size(); i++) {

            clan cl = (clan) llista.get(i);
            //System.out.println(jug.getNom());
            Vector oneRow = new Vector () ;
            oneRow. add (Integer.toString(cl.getId_clan()) );
            oneRow. add (cl.get_nom());
            oneRow. add (cl.get_nivell());
            oneRow. add (cl.get_copes());
            oneRow. add (cl.get_jugadorAdmin());
            oneRow. add (cl.get_tipus());
            
            //oneRow.add(jug.getClan ());
            model.addRow (oneRow);

        }

        tablaC.setModel(model);
    }//GEN-LAST:event_actualitzaCActionPerformed

    private void eliminarClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClanActionPerformed
        // Anem al daogeneric, a la funcio deleteClan i elimina el parametre id_clan
        DaoGeneric.getInstance().deleteClan(Integer.parseInt(id_clan.getText()));
    }//GEN-LAST:event_eliminarClanActionPerformed

    private void crearClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClanActionPerformed
        try { // Creem un nou constructor de nom clan amb tots els parametres necesaris
            clan cl = new clan(nomC.getText(), Integer.parseInt(nivellC.getText()), Integer.parseInt(copesC.getText()), 
                    Integer.parseInt(jugadminC.getText()), tipusC.getText());
            //"xgaaa", 233, 123, "clanet", 12,333) ;
            
            // Ens crea la instancia
            DaoGeneric.getInstance().create(cl);
            
        } catch (Exception exc) { // Si no pot ens sortira l'error 
            JOptionPane.showMessageDialog(null, "Error al guardar " + exc.getMessage());
        }
    }//GEN-LAST:event_crearClanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualitzaJ;
    private javax.swing.JButton actualitzaC;
    private javax.swing.JButton actualitzaP;
    private javax.swing.JTextField copes;
    private javax.swing.JTextField copes1;
    private javax.swing.JTextField copesC;
    private javax.swing.JButton crearClan;
    private javax.swing.JButton crearJugador;
    private javax.swing.JButton crearPartida;
    private javax.swing.JButton eliminarClan;
    private javax.swing.JButton eliminarJugador;
    private javax.swing.JButton eliminarJugador1;
    private javax.swing.JTextField estrelles;
    private javax.swing.JTextField estrelles1;
    private javax.swing.JTextField gemes;
    private javax.swing.JTextField gemes1;
    private javax.swing.JTextField id_clan;
    private javax.swing.JTextField id_jug;
    private javax.swing.JTextField id_partida;
    private javax.swing.JTextField idjug1;
    private javax.swing.JTextField idjug2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jugadminC;
    private javax.swing.JTextField nivell;
    private javax.swing.JTextField nivell1;
    private javax.swing.JTextField nivellC;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField nomC;
    private javax.swing.JTextField oro;
    private javax.swing.JTextField oro1;
    private javax.swing.JTextField resultat;
    private javax.swing.JTable tablaC;
    private javax.swing.JTable tablaJ;
    private javax.swing.JTable tablaP;
    private javax.swing.JTextField temps;
    private javax.swing.JTextField tipus;
    private javax.swing.JTextField tipusC;
    // End of variables declaration//GEN-END:variables
}
